language: nix

before_deploy:
  - mkdir pages
  - cp -f ./result pages/main.pdf

deploy:
  local-dir: pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
